### ISSUE TITLE
Structure docs 

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#10]
Structure docs according to:
- Core (getaction, setreward, including small examples)
- Stats (calls for getting theta, getting logs)
- Admin (calls for the front-end)
- Custom scripts: explanation of the available objects when writing custom scripts.

**Comment by g0ulash** [comment]
Docs are currently structured:
- Core
- Stats
- Admin

Custom scripts is still on the todo lists.

**Comment by MKaptein** [comment]
Libs & Experiment still need documentation.
- Experiment: document all the calls that can be made from the "custom" code.
- Libs: document the libs themselves
- Add section "Contributing Libs" describing how a lib should be written, and that is should have a test file in utils.

**Comment by g0ulash** [comment]
Closing this issue for now. The documentation at http://mkaptein.github.io/streamingbandit is up-to-date as is.
