### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#12]
Allow multiple users to login to the back-end management and only see their own experiments.

**Comment by g0ulash** [comment]
Inspiration for user-management:

- https://pypi.python.org/pypi/torcms
- https://github.com/mehmetkose/tornado-user-authentication-example/blob/master/app.py
- https://github.com/puentesarrin/selene
- https://github.com/PlaidCloud/dustdevil
- https://www.surf.nl/diensten-en-producten/surfconext/diensten-aanbieden-en-afnemen-via-surfconext/als-instelling-zelf-diensten-aanbieden-via-surfconext/index.html (but I guess this is needed in combination with any of the above)

**Comment by MKaptein** [comment]
Add an "admin"-"admin" user to mongoDB on startup of the app, and make sure that the addUser endpoint is protected.

**Comment by g0ulash** [comment]
Do we want an admin to be able to recover his password? (i.e., make a second script which reinstates the admin password)

**Comment by MKaptein** [comment]
No, let’s not. If people have access to the DB they can do this anyway; we might at some point implement a call to reset the password, but not now.

**Comment by g0ulash** [comment]
I don't mean a call. I mean a separate script supplied with the package setup/distribution that the user who has the access to the instance can run it.

**Comment by MKaptein** [comment]
Yes, I got that; still “No”; if someone has access they can restore it in Mongo; I guess that’s enough for now no?

**Comment by g0ulash** [comment]
Fixed the AddUser for admin-only. Tested and working. See 91b9c02
