### ISSUE TITLE
Replace hardcoded base url "http://localhost:8080"

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#13]
Currently BASE_URL has been hard coded "http://localhost:8080" in several places (i.e. in admin.js and in the agents scripts).

Probably better to either dynamically retrieve StreamingBandit's base URL or make it configurable in one place, that is, in the config.cfg.

**Comment by g0ulash** [comment]
You are right about the hard-coding in admin.js. I can put a base URL in config.cfg, but the only part that will actually be configurable is the port - I will probably try to do that.

Regarding the agents, I guess you can make a statement for it that they can be seen as "separate" agents and for example purposes it is probably less uncluttered than loading the URL from a config file.

**Comment by robinvanemden** [comment]
Thank you for your answer! 

Though I gather that for some use cases, it might still be useful to be able to configure the full URL, and not just the port number - for example, here, StreamingBandit runs on a server  and my dev environment runs on a workstation. When I login to and work on the the server over SSH, localhost makes perfect sense. Yet when I access the web interface directly from my workstation, the hard-coded localhost in admin.js is rather inconvenient?

**Comment by g0ulash** [comment]
You mean running the front-end separately from the back-end? In our case though, the front-end and back-end are quite intertwined, right? I am not sure how and why you would run the web-interface from your workstation.

Or do you mean that you access the web interface that is running on the server from your workstation (so you're still accessing files from the server)? In that case, how would the hard-coded localhost have a bad influence on the performance? (Sorry, I am not really good at JavaScript, so I might be ignorant here.)

**Comment by robinvanemden** [comment]
I was referring to the latter. As the JS is run by/on the workstation, localhost would then refer to the workstation, not to the server. There are many ways to remedy this - one, probably more elegant, solution would be to just use a relative URL in the JS. So instead of 

```
http://localhost:8080/1/getAction.json?key=3285c378fe
```

you'd link to 

```
/1/getAction.json?key=3285c378fe
```

**Comment by MKaptein** [comment]
Hey hey,

Yeah, I think at least those “test” calls from the interface should be made relative; its a quite natural useless that the management console is used from somewhere else then localhost. Actually, if I hard-coded that in then apologies, that’s quite stupid…

Cheers,

Maurits
