### ISSUE TITLE
Default values in setReward for ABC test

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#14]
Seems that the following in "ABC test" setReward() 

``` python
n = self.get_theta().get("n",1) + 1
self.set_theta({"n":n})

# If still running increase action count
if N==0 or n<N:
    d = self.get_theta(action={'choice':self.action['choice']})
    s = d.get("s",1) + self.reward
    n = d.get("n",2) + 1
    self.set_theta({"s":s, "n":n}, action={'choice':self.action['choice']})
```

should be

``` python
n = self.get_theta().get("n",0) + 1
self.set_theta({"n":n})

# If still running increase action count
if N==0 or n<N:
    d = self.get_theta(action={'choice':self.action['choice']})
    s = d.get("s",0) + self.reward
    n = d.get("n",0) + 1
    self.set_theta({"s":s, "n":n}, action={'choice':self.action['choice']})
```

Otherwise, the the n counter after the first choice will be 2 , not 1, for theta and 3 instead of 1 for theta:choice. Also, reward will start at 1 plus the reward of a particular choice, instead of just the reward value of that particular choice.

**Comment by MKaptein** [comment]
I would say both are incorrect; we should make use of the count and mean objects in base, and use their updates... :S

Verstuurd vanaf mijn iPhone

**Comment by robinvanemden** [comment]
Agreed - though that is a change at a different level of abstraction. The suggested change does count correctly :) Also, I see that work is being done on these files in dev - so this issue might be superfluous anyway.

**Comment by robinvanemden** [comment]
Same goes for things like the import of the base lib in lm.py - it states 

``` python
from list.base import *
```

Which obviously should be 

``` python
from libs.base import *
```

yet I see that a recent commit states that "Big update, lm.py is not finished yet.", so I might just leave this code alone and concentrate on "my" LiF code?

**Comment by MKaptein** [comment]
The start value for counts is tricky; you don't want to divide by 0 when computing a mean... The default base mean starts with n=2, s=1, reflecting a uniform prior on a proportion...

But we should be using our libs, if we don't, then who will ;)?

Verstuurd vanaf mijn iPhone

**Comment by MKaptein** [comment]
Jules is working on the examples and finishing base and lm; paper deadline is coming Monday, and then it should move to the master branch.... (And hence be working. And using the libs in the AB test example ;)) thanks for spotting that one!

Verstuurd vanaf mijn iPhone

**Comment by robinvanemden** [comment]
Super that things are moving along so quickly!

**Comment by MKaptein** [comment]
Also, if we don't use them because they are not useful, then we should fix that ;)

Verstuurd vanaf mijn iPhone

**Comment by MKaptein** [comment]
I guess this discussion is relevant but we should revisit it when reconsidering the libs (before pushing them to the main branche). I am going to close the issue for now.
