### ISSUE TITLE
Store backups of setReward and getAction scripts

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#18]
It would be great to be able to revert to backed up versions of the setReward and getAction scripts for a single experiment. 

Obviously, it would also be cool to add scripts to defaults more easily then is now the case.

**Comment by g0ulash** [comment]
Currently, deleting an experiment includes a bug as well. When deleting an experiment it stays in Redis and when creating a new experiment the numbering goes on where it left (so deleting Experiment 1 and then creating another experiment will result in Experiment 2). It is rather minor, but we need to distinguish the archived and non-archived experiments in Redis. (Or perhaps transfer them to Mongo?)
