### ISSUE TITLE
Ability to run tests/agents from the front-end (debug current agents)

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#19]
Can we in some way create the ability to submit a python script that runs a test of an experiment? That would make interactive development in the front-end much easier....

**Comment by g0ulash** [comment]
We already have some agents in the utils folder, but it would be best to integrate them into StreamingBandit's front-end (these need to be debugged again). Furthermore, we have a tiny bug in the front-end for testing the setReward/getAction calls (the try-out button) which is hardcoded to localhost. See #13.

- Check and debug all the agents
- Integrated agent system in front-end
- Making try-out of experiments easier

**Comment by MKaptein** [comment]
I guess we now have the simulate call implemented so this should be solved...
