### ISSUE TITLE
Parsing lists in dict to Redis

### ISSUE THREAD

**Issue by g0ulash** [MKaptein/streamingbandit#21]
When inserting a list inside of a dictionary to redis (i.e. when using the tolist() function from numpy to store an array), redis obviously saves this as a string, for example:

theta = { 'b' : [1,0], 'A' : [[1,0],[0,1]] }

will become

theta = { 'b' : '[1,0], 'A' : '[[1,0],[0,1]]' }

once extracted again from redis. We can fix this using the ast.literal_eval() function from the ast package. However, the question is where to evaluate this output behavior. In the Experiment class, Database or should we leave it up to the implementation of the models themselves?

**Comment by g0ulash** [comment]
Currently, I am working on a linear model, and as a workaround I have written this inside the implementation of the model itself. Another note, this is also the case with everything that is not a string, it seems. Ints, lists, whatever...

**Comment by MKaptein** [comment]
Can someone check the status on this one?

**Comment by g0ulash** [comment]
This is not a bug, but intended behavior. Using ast.literal_eval() is perfectly fine.
