### ISSUE TITLE
Ability to do setReward calls based on advice ID/key

### ISSUE THREAD

**Issue by g0ulash** [MKaptein/streamingbandit#27]
The ability to do a setReward call based on advice ID would be helpful. In this way, one does not need to repeat the context+action in the setReward call.

How it works:

1. A getAction call like: http://localhost:8080/1/getAction.json?key=xxx&context={x:y}
2. This returns a JSON as follows: {"action" : z, "advice_id" : YYY}
3. A setReward call: http://localhost:8080/1/setReward.json?key=xxx&advice_id=YYY&reward=1

Perhaps we can let the user choose what he wants using a flag in the getAction call, like so:

http://localhost:8080/1/getAction.json?key=xxx&context={x:y}&advice_id=True

(With standard being False)

**Comment by g0ulash** [comment]
Another possibility: instead of using a flag in the getAction, make a flag in the front-end (when setting up the experiment).

**Comment by MKaptein** [comment]
I guess this is implemented in the new version; I am closing this issue.
