### ISSUE TITLE
Stay compatible with Python 2.7 - or not?

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#30]
StreamingBandit does not seem to work nicely with Python 2.7 (anymore). 

When running the server on 2.7 I first encountered:
```
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    from handlers import evalhandlers
  File "/var/www/test/streamingbandit_latest/app/handlers/evalhandlers.py", line 10, in <module>
    import _pickle
```

Which can be fixed easily enough by replacing **import _pickle** by **import pickle**.

The next error has to do with the # -*- coding: utf-8 -*- headers wreaking havoc on the code executed by "exec". 

So I removed those.

At that point, another problem popped up: libraries where not imported correctly. Which made me wonder if we might better give up on efforts to stay Python 2.7 compatible? Does not seems to worth the time and effort? What do you think?

**Comment by MKaptein** [comment]
Hey hey,

Yes, let’s drop 2.7 (I was passed that in my head already…)

Cheers,

Maurits

**Comment by robinvanemden** [comment]
Agreed! Then it is probably a good idea to remove "untested with python 2.7" from the README, and just state "python 3.x+"

@g0ulash can probably make that change easiest by just editing the README within GitHub?

**Comment by MKaptein** [comment]
Yes,

Or used: “Tested on 2.7 and confirmed broken" ;)
