### ISSUE TITLE
Follow REST specs when setting resources / paths

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#33]
At the time, we have all kinds of calls with different styles of resource definitions and paths. You don't really want that - it makes connecting rest based frameworks more difficult. For an idea of how these things are mostly setup:

- [JSONPlaceholder](http://jsonplaceholder.typicode.com/)
- [RestApiTutorial](http://www.restapitutorial.com/lessons/restfulresourcenaming.html)
- [An illustrative image](https://raw.githubusercontent.com/metosin/compojure-api/master/examples/reusable-resources/screenshot.png)
- etc 

That means our api would work something like this:

```
What you want to do   How to call a REST api to get this done

GET_LIST              GET http://my.api.url/posts?sort=['title','ASC']&range=[0, 24]&filter={title:'bar'}
GET_ONE               GET http://my.api.url/posts/123
CREATE                POST http://my.api.url/posts/123
UPDATE                PUT http://my.api.url/posts/123
DELETE                DELETE http://my.api.url/posts/123
GET_MANY              GET http://my.api.url/posts?filter={ids:[123,456,789]}
GET_MANY_REFERENCE    GET http://my.api.url/posts?filter={author_id:345}
```
So use just one level deep resources, without .json, not:
`GET /admin/exp/list.json`
but:
`GET /exp`

Not:
`GET /admin/exp/123/get.json`
but
`GET /exp/123`

Not:
/admin/user/add.json?username=USERNAME&password=PASSWORD 
but: 
```
POST /users
 Parameters
 username:username 
 password:password
```
If we would be exposing our API according to ie http://jsonplaceholder.typicode.com/  I would say we are doing well?

**Comment by MKaptein** [comment]
Hmm..

Feel free to change them to something simpler (in the handlers files it's easy to change). However, "exp" in your example doesn't indicate it would get a list of multiple experiments, nor that you need to be logged in (admin). So, the current names are chooses to communicate all that...  perhaps that is not standard anymore?

Simpler is better I would say, but not too simple ;S

Verstuurd vanaf mijn iPhone

**Comment by robinvanemden** [comment]
In general, in REST-land, it is expected that when you GET exp, you get all experiments that are available to the user, based on his/her rights. If you want one exp, you GET exp/123, etc.  Currently there are already calls for all of those, they just aren't following this pattern.

In other words, to access the exp resource(s), you do exp, and get what you need according to your role / permissions?

**Comment by robinvanemden** [comment]
Of course, if you don't want to offer a list of experiments, you still follow the pattern, yet return 501 Not Implemented.

**Comment by MKaptein** [comment]
Haha,

I was just reading some of your examples, and I can't really see why the /admin/ etc does not align with this; to me it's intuitive (but hey, I created a bunch of them ;))

Just make a suggestion that you think is best (you are the REST guru); it's an easy fix!

By the way, any sneak preview available for the front-end? I am curious!

Verstuurd vanaf mijn iPhone

**Comment by robinvanemden** [comment]
I know you follow a different pattern there - I think I commented on that with regards to your book as well ;)

**Comment by robinvanemden** [comment]
First sneak = soonish :)

**Comment by robinvanemden** [comment]
If we really want to differentiate between an /admin/.. route and non-admin /.. based routes, that's something we could do - but "follow REST best practices" is a good idea regardless, I'd say - ie not define an endpoint with get.json, when you already GET something and know the API returns json.

**Comment by MKaptein** [comment]
I would be happy to adopt something more standard, so just make a suggestion (and I can change the book to ;))



Verstuurd vanaf mijn iPad

**Comment by MKaptein** [comment]
Ow, so, the .json actually came from a best practice document; to set it apart from (e.g.) csv or xml...

Again just suggest them the way you would like them; this was done using a best practice example, but I guess an old one?



Verstuurd vanaf mijn iPad

**Comment by robinvanemden** [comment]
Now I am curious as to that best practice document :)
I will suggest a list of endpoints that seem nice to me - in the end, its all up to us:

> Unlike SOAP-based Web services, there is no "official" standard for RESTful Web APIs. This is because REST is an architectural style, while SOAP is a protocol. REST is not a standard in itself.

**Comment by MKaptein** [comment]
Yes, it's up to us, but you are most experienced so doing it like you would "expect" it is probably our best bet ;)

Verstuurd vanaf mijn iPhone

**Comment by g0ulash** [comment]
The following is possible: (i.e., implicit parameters in the POST call)
```
POST /users
 Parameters
 username:username 
 password:password
```

We can do this by changing from self.get_argument() to self.get_body_argument() (if I remember correctly), see:

https://stackoverflow.com/questions/34818996/tornado-what-is-the-difference-between-requesthandlers-get-argument-get-qu

**Comment by robinvanemden** [comment]
@g0ulash : Exactly!

Also, @g0ulash and @MKaptein , my "RESTful" endpoint suggestions - only for Adminstration and Core API's, the others are fine as is. (Added them to the right of the app.py calls below). 

```
########## Handlers ##########

    # Core API
    (r"(?i)/(?P<exp_id>\w+)/getaction.json", corehandlers.ActionHandler),                       GET     /getaction/(?P<exp_id>\w+)
    (r"(?i)/(?P<exp_id>\w+)/setreward.json", corehandlers.RewardHandler),                       POST    /setreward/(?P<exp_id>\w+)

    # Adminstration API
    (r"(?i)/admin/exp/add.json", adminhandlers.AddExperiment),                                  POST    /exp
    (r"(?i)/admin/exp/list.json", adminhandlers.GetListOfExperiments),                          GET     /exp
    (r"(?i)/admin/exp/defaults.json", adminhandlers.ListDefaults),                              GET     /exp/defaults
    (r"(?i)/admin/exp/default/(?P<default_id>\w+)/get.json", adminhandlers.GetDefault),         GET     /exp/defaults/(?P<default_id>\w+)
    (r"(?i)/admin/exp/(?P<exp_id>\w+)/get.json", adminhandlers.GetExperiment),                  GET     /exp/(?P<exp_id>\w+)
    (r"(?i)/admin/exp/(?P<exp_id>\w+)/delete.json", adminhandlers.DeleteExperiment),            DELETE  /exp/(?P<exp_id>\w+)
    (r"(?i)/admin/exp/(?P<exp_id>\w+)/edit.json", adminhandlers.EditExperiment),                PUT     /exp/(?P<exp_id>\w+)
    (r"(?i)/admin/exp/(?P<exp_id>\w+)/resetexperiment", adminhandlers.ResetExperiment),         GET     /exp/(?P<exp_id>\w+)/resetexperiment
    (r"(?i)/admin/user/add.json", adminhandlers.AddUser),					POST    /user



    # Statistics API --> zijn prima, allemaal getters

    (r"(?i)/stats/(?P<exp_id>\w+)/currenttheta.json", statshandlers.GetCurrentTheta),
    (r"(?i)/stats/(?P<exp_id>\w+)/hourlytheta.json", statshandlers.GetHourlyTheta),
    (r"(?i)/stats/(?P<exp_id>\w+)/log.json", statshandlers.GetLog),
    (r"(?i)/stats/(?P<exp_id>\w+)/actionlog.json", statshandlers.GetActionLog),
    (r"(?i)/stats/(?P<exp_id>\w+)/rewardlog.json", statshandlers.GetRewardLog),
    (r"(?i)/stats/(?P<exp_id>\w+)/summary.json", statshandlers.GetSummary),

    # Login API--> zijn prima 

    (r"(?i)/login", managementhandlers.LogInHandler),
    (r"(?i)/logout", managementhandlers.LogOutHandler),
               
    # Simulation API  --> prima

    (r"(?i)/eval/(?P<exp_id>\w+)/simulate", evalhandlers.Simulate),
]
```

**Comment by g0ulash** [comment]
I think your suggestions are alright. We have to take quick action on this though, because there are quite some places where we have to change the documentation of these endpoints (i.e., paper and documentation).

**Comment by MKaptein** [comment]
Ok, let's do this one first ;)

**Comment by MKaptein** [comment]
Hmmm.. als we dan toch de "simpele" calls aanhouden, laten we dan ook de "/stats/ ertussenuit halen bij de stats calls.

**Comment by MKaptein** [comment]
Check whether the docs are correct, also specifying input parameters (JSON yes/no, etc) and return values. Good to do one more check for each call before moving on.

**Comment by g0ulash** [comment]
For some annoying reason I can't really get the Example docstrings quite right. I have updated every docstring and endpoint. Everything should be fine as is, however, I will leave this issue open so I can return to check/fix the example tables.

**Comment by g0ulash** [comment]
Since we will be using snake_cases for variables in the software (#48), will we be using snake_cases in the endpoints as well? (Right now the endpoint accepts any cases, so lower/uppercase doesn't matter, but it doesn't accept snake cases.) 

EDIT: I have decided to leave the endpoints as is. If anyone has objections, please let me know a.s.ap.

**Comment by robinvanemden** [comment]
For endpoints, it is recommended to use spinal-case (which is highlighted by [RFC3986](https://tools.ietf.org/html/rfc3986)), this case is used by Google, PayPal and other big companies. 

But I agree with leaving the endpoints as is. No need for separators in endpoint definitions as short as ours.

**Comment by MKaptein** [comment]
Robin?

**Comment by robinvanemden** [comment]
@MKaptein : did you ask "Robin?" before or after https://github.com/Nth-iteration-labs/streamingbandit/issues/33#issuecomment-331397619

**Comment by MKaptein** [comment]
before.
