### ISSUE TITLE
Add additional CORS related header to BaseHandler

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#34]
Add additional CORS header to BaseHandler:

`self.set_header('Access-Control-Allow-Headers', 'origin, content-type, accept, authorization')`

**Comment by robinvanemden** [comment]
PS: I may have to investigate a little here, where and when this header is needed. Reassigned to self :)

**Comment by g0ulash** [comment]
Yes, as you can see in: [streamingbandit/app/handlers/basehandler.py](url). We have the following:

`    def set_default_headers(self):
        self.set_header("Access-Control-Allow-Origin", "*")`

If need be, we can add extra headers.

**Comment by robinvanemden** [comment]
Thanks - found it as well, but missed it at first somehow 👍 
Should get some coffee I guess :)
