### ISSUE TITLE
Set UpdateExperiment get content-type header to "application/json"

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#36]
For some reason that is not yet clear to me, when you explicitly need to set response type json to (at least, will test some more) UpdateExperiment get, like so:

```
class UpdateExperiment(BaseHandler):
    
    def get(self, exp_id):
        ...
        self.write(json.dumps(response))      
        self.set_header("Content-Type", "application/json")
        ...
```

**Comment by g0ulash** [comment]
I can set a Content-Type in the BaseHandler, but this means that every single call will return an application/json from now on (GET, PUT, POST, DELETE)

**Comment by robinvanemden** [comment]
Setting the Content-Type to application/json would be perfect for our REST API endpoints. 
But we did decide to return an HTML template in #31 
Does setting the BaseHandler Content-Type to application/json interfere with that?

**Comment by g0ulash** [comment]
I made the handler that handles the HTML page to not inherit the base class - it will just inherit Tornado's RequestHandler. So I'll set the Content-Type for application/json for all REST API endpoints then - I will put it in the set_default_handlers() in BaseHandler.
