### ISSUE TITLE
When accepting a JSON Request Body use tornado.escape.json_decode

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#37]
In principle, REST clients posts a JSON request to the server, not form data. The latter needs to be decoded using:

`tornado.escape.json_decode(self.request.body) `

Relevant for all JSON calls that send data via the body. These currently make use of `self.get_body_argument("getcontext")`

See for example:

- https://stackoverflow.com/questions/15614021/how-to-fetch-json-argument-in-handler-json-is-in-body-of-post-request-with-no-k
- https://stackoverflow.com/questions/16451660/tornado-request-body
- https://www.quora.com/In-Tornado-how-can-I-access-POST-parameters
- https://technobeans.com/2012/08/26/tornado-escape-json/

**Comment by MKaptein** [comment]
Just to be sure; with this issue you intend to say that **all** rest calls should not accept post variables but rather accept a single variable ("body"?) that contains a JSON in which all the requested data is stored?

Now, would that also imply that you want the (e.g.,) setreward call to not accept multiple JSON files (for the reward, the context, and the action), but rather a single one with all of these in it?

That's I guess quite some work and I am trying to understand the advantages of this over the current setup; is it just more standard in REST-land? Or are there additional reasons to prefer this?

**Comment by MKaptein** [comment]
Also, should that also hold for the GET calls?

**Comment by robinvanemden** [comment]
From  https://www.ibm.com/support/knowledgecenter/en/SS8NMD_6.1.2/com.ibm.ucbuild.doc/topics/rest_api_ref_conventions.html

> The basic create, read, update, delete operations are provided according to common REST API conventions. The top-level URL for an element type represents the collection of items of that type. To render the list of all elements of that type as an array of JSON objects, use the HTTP method GET with appropriate HTTP headers or the json query parameter. To create a new element, use the HTTP method POST to the top-level URL for the appropriate type and **provide JSON data for the element in the body of the request**.

Of course, with GET, you send the info in the URL. So GET should not be a problem.

**Comment by robinvanemden** [comment]
May not be too big a thing to change this in the code? Currently, you use form-data, which is in essence just another way to format the data which is then sent in the body. We can discuss this later today, of course!

**Comment by MKaptein** [comment]
Hmmm…

Later is not good :S We need to make a decision, plan it out, and implement it. Since these are all things we need in the write-up too, we have to decide whether or not to include them.

**Comment by g0ulash** [comment]
So what's the downside of using form-data?

**Comment by robinvanemden** [comment]
It's a convention thing. If clients by default expect they need to send JSON, and instead they receive form data, there needs to be additional parsing of the data by the client, adding complexity there.

**Comment by g0ulash** [comment]
I think I can fix this without too much hassle. Is this also needed for PUT requests?

**Comment by robinvanemden** [comment]
I gathered as much - that's great! And yes, the same with PUT requests.

**Comment by g0ulash** [comment]
Fixed in commit d0f58a2
