### ISSUE TITLE
Understand, and limit, the "exec()" function.

### ISSUE THREAD

**Issue by g0ulash** [MKaptein/streamingbandit#4]
MKaptein: "The exec function can be "more secure" by limiting the number of calls it will accept. We should look into this to secure the code."

**Comment by g0ulash** [comment]
Here's an article on the dangers of the eval() and exec() functions: [http://nedbatchelder.com/blog/201206/eval_really_is_dangerous.html](url)

So allowing "untrusted" code on the exec() function is dangerous and should not be used. If you read the comments, you can try to sandbox parts of python. However, this also never guarantees safety.

One solution I come to think of, is to use a parser. For example, python's ast could be a good solution ([https://docs.python.org/2/library/ast.html](url)). This allows us to control everything that is put into the getAction and setReward codes. This also allows us to make our "own", easy language - although this is better for the less-technical people that will use StreamingBandit, this does not have a high priority.

Using a parser would probably need quite some work, but I think it can be worthwhile in the end.

**Comment by g0ulash** [comment]
Especially when considering implementing a user-management system, where multiple users will be getting access to only their own experiments, we must ensure that you cannot escape the exec() function.

**Comment by g0ulash** [comment]
We should definitely look into this: http://restrictedpython.readthedocs.io/en/latest/

**Comment by g0ulash** [comment]
I think this is still an issue we should check before the newest release. Looking at the following GitHub page, I think it's very easy to implement for us, and makes the application much, much safer:

https://github.com/zopefoundation/RestrictedPython

**Comment by g0ulash** [comment]
An update on this: RestrictedPython is not well documented and I cannot get it working flawlessly.

I found out, however, another way of restricting the exec() function: by limiting the builtins directly in the exec code. An example:

Let's say I have the following code:

```
source_code = """
import os
os.listdir()
"""
```

This is code we probably do not want to run. We can limit this by using compile and exec in the following way:

```
byte_code = compile(source_code, filename = '<inline_code>', mode = 'exec')
exec(byte_code, {'__builtins__' : {}}, None)
```

Running this will give the following error:

```
ImportError: __import__ not found
```

So currently, running compile and exec like this will restrict the code to not be able to import anything!
We can allow this code to run by doing the following:

```
byte_code = compile(source_code, filename = '<inline_code>', mode = 'exec')
exec(byte_code, {'__builtins__' : {'import' : __import__}}, None)
```

However, we probably don't want everybody to be able to import just any code. What we can do to make our environment more restricted, is importing the packages that we allow in the builtins, but we have to note that this will somewhat change the way that we use the code.

An example for how future code would look like:

```
prop = base.Proportion({})
prop.update(1)
print(prop.get_value())
```

And the builtins, compile and exec would look as follows:

```
import libs.base as base
safe_builtins = {}
safe_builtins['print'] = print
safe_builtins['base'] = base

byte_code = compile(source_code, filename = '<inline_code>', mode = 'exec')
exec(byte_code, {'__builtins__' : safe_builtins}, None)
```

This will substantially change the way we would code though (since we will not allow any imports to happen).

An example of safe_builtins to use in StreamingBandit would then be:

```
safe_builtins = {'print' : print, 'base' : base, 'numpy' : np, 'np' : np, 'scipy' : sp, 'sp' : sp, 'bts': bts, 'lm' : lm, 'lif': lif, 'thompson' : thompson, 'tbl' : thompson_bayesian_linear, 'random' : random}
```

EDIT: I haven't tested this fully in StreamingBandit yet - will do that today. It might lead to problems in terms of scoping of code (i.e. not sure if 'self' is still defined and if the numpy seed will still be handed on...)

**Comment by robinvanemden** [comment]
I just tested the latest safe_builtins version on our strm server with our AB and the LiF defaults. Works perfectly! I did need to change Pow(x,y) to x**y in the LiF default - but we can always decide to add pow and/or other functions to builtins if we deem them useful.

**Comment by g0ulash** [comment]
We can add such functions indeed. We should cross-check the following list and see which functions we want to allow:

https://www.programiz.com/python-programming/methods/built-in
