### ISSUE TITLE
defaults add "Thompson (bernoulli)"

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#42]
We need an example default for Thompson sampling for the k-armed bernoulli bandit.

- getcontext code: {} # Empty

- getaction code:
This is the minimal verion:
```
# Number of arms
k = 4 
# For each arm get draw
for(i in k){
    action[i] <- draw.from.posterior()
}
# Play highest draw
max(action[i])
```
Note that the propensity is harder to compute exactly in this case. One option would be:
```
# Number of arms
k = 4 
# For each arm get 1000 draws
for(i in k){
    action[i] <- draw.from.posterior(1000)
}
# For each 1000 draws
for(d in 1000){
    # Store how often each arm "won" out of the 1000 trials
    store k:#wins
}
# choose action with probability #wins / 1000
propensity = #wins / 1000 for selected action.
```
    
- getreward code:
```
# Arm probablities increase linearly:
r = binomial(p = .2 * k)
```

- setreward code:
update the appropriate proportion reward for the action.

**Comment by g0ulash** [comment]
Since we have implemented Thompson sampling in the libraries, our get_action code looks as follows:

```
import libs.thompson as thmp
propl = thmp.BBThompsonList(self.get_theta(key="Treatment"), ["1","2","3","4"])
self.action["Treatment"] = propl.thompson()
```

And our set_reward code looks as follows:

```
import libs.base as base
prop = base.Proportion(self.get_theta(key="Treatment", value=self.action["Treatment"]))
prop.update(self.reward["value"])
self.set_theta(prop, key="Treatment", value=self.action["Treatment"])
```

Not sure if you want to change this or not? And I am also not sure how to compute the propensity then.

**Comment by MKaptein** [comment]
I guess we should add the computation of the propensities to the library. Here is an [R] implementation:
```
a1 <- c(10, 12)		# Successes and failures arm1
a2 <- c(5,20)		# Successes and failures arm2

# Do sampling:
n <- 1000
d1 <- rbeta(n, a1[1], a1[2])
d2 <- rbeta(n, a2[1], a2[2])

# Computer propensities arm 1 and 2:
prop1 <- sum(d1>d2) / n
prop2 <- sum(d2>d1) / n

# Check, in this case:
prop1 + prop2  # = 1
```

We can just add:
```
self.action["propensity"] = propl.thompson_propensity(self.action["Treatment"], k=1000)
```
To the get_action code. (you have to pass the selected arm, and the number of simulation draws)

**Comment by MKaptein** [comment]
Ow, and sorry for the [R] example, I am just faster in [R]
And Ow2; obviously to extend this to k arms you need to find out of the n samples how often arm k won.

**Comment by MKaptein** [comment]
And, sorry for the rant, ideally thompson_propensity has a parameter for n, where the default is (say) 1000, but it can be decreased for speed, and increased for large k.

**Comment by g0ulash** [comment]
@MKaptein In https://github.com/Nth-iteration-labs/streamingbandit/issues/42#issuecomment-331938903 you give code that computes two propensities, is this really necessary when you only want 1 propensity? Or is this just to check if they add up to 1? If it's not necessary, it's computationally less expensive to only compute 1 instead of all K propensities.

**Comment by MKaptein** [comment]
We need only one, namely of the selected arm.
