### ISSUE TITLE
default: BTS linear model

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#44]
We need a BTS / Linear model combination default. Most of it is there, but I would do a simple data generation in which the aim is to select a good price (action) to maximize revenues (reward) on two different devices (context)

- getcontext:
```
# Simple equal probability context web or mobile
device = sample("web", "mobile")
```

- getaction:
Aim is to choose a price to maximize revenue:
```
Model  price ~ 1 + price + price^2 + device(0,1) + device*price + device*price^2
And do BTS
```
(note, again no propensity because of the continuous price)

- get reward:
```
pr(r=1) = logit(  .1 * ((price+ (device*4) )-10)^2   # Highest probalbity at 10 or 14.
buy = binom(p=(r=1)
```

- set reward:
Do BTS online update using buy * price as dependent variable

**Comment by g0ulash** [comment]
In your pseudocode, when you say sample("web", "mobile"), do you want that sample to return an int or something? How else would you use "device" in the model?

**Comment by MKaptein** [comment]
Well,

either one passes int’s, or, in the code, do:

x <- offense(device==“mobile”,0,1)

Both are fine.

**Comment by g0ulash** [comment]
What do you mean with the function "offense".

As far as I understand it now, you mean something like
```
if device == "mobile":
    x = 1
else:
    x = 0
```

**Comment by g0ulash** [comment]
I did random.randint(1,2) (gives either a 1 or 2).

**Comment by MKaptein** [comment]
haha,

auto complete; ifelse()

That’s an R function that indeed implements what you just wrote!

**Comment by g0ulash** [comment]
I'm currently testing this one. I'm confused by the implementation. @MKaptein you stated the following for the get_reward code:

```
pr(r=1) = logit(  .1 * ((price+ (device*4) )-10)^2   # Highest probalbity at 10 or 14.
buy = binom(p=(r=1)
```

But it should be the logistic function instead of the logit function, right?

**Comment by MKaptein** [comment]
No clue what the name is in python; it should be https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.special.expit.html <https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.special.expit.html>

**Comment by g0ulash** [comment]
You're right, but your code had the "logit" function so I was confused (as logit is log(x) - log(1-x) and not 1 / (1 + exp(-x)) ). I have fixed this.
