### ISSUE TITLE
actionlog and rewardlog call need parameter to specify the number of rows

### ISSUE THREAD

**Issue by MKaptein** [MKaptein/streamingbandit#47]
The stats/actionlog/<id> call should have a parameter specifying the number of rows to return with default value 100.

This is useful to limit the size of the resulting object, and useful to be able to display the log in the front-end.

**Comment by g0ulash** [comment]
Do we want the same limit for the other log retrieval calls such as the manually logged items and hourly theta?

**Comment by MKaptein** [comment]
yes! Let’s.
