### ISSUE TITLE
Error handling: Proper and informative errors.

### ISSUE THREAD

**Issue by g0ulash** [MKaptein/streamingbandit#5]
Error when not giving a valid advice_id (as in, not a valid ObjectId, i.e. a non 24-character hex string, such as 0, XXX, 1, 123 etc.)

**Comment by VincentGijsen** [comment]
this is probably a result of a mongo-db query failing, as it it looking for a ObjectId, I would opt it as a bug, rather than 'enhancement'

**Comment by MKaptein** [comment]
Well, that was just one example I guess of erroneous error logging (and actually the advice IDs have been removed from this open version). But, throughout we might benefit from better error logging.

**Comment by g0ulash** [comment]
The following website shows a nice way of handling errors: http://nanvel.com/b/1417907640

I think using this kind of error handling is easy enough to implement and very flexible. Instead of casting a JSON, we could of course also serve a webpage which may be nicer formatted - but that does not necessarily add value.

**Comment by MKaptein** [comment]
It would be great if we could throw errors if the (e.g.,) datatypes of the custom calls are not well defined and then it will be a JSON object that is returned when the REST call is made which contains an informative error for those implementing the code.

**Comment by MKaptein** [comment]
Error handling has improved and errors are now caught. I guess this is dealt with, but we can reopen one if we find new problems...
