### ISSUE TITLE
Set handler to BaseHandler in ListDefault and ListDefaults

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#50]
In handlers/adminhandlers.py 

`class ListDefaults(tornado.web.RequestHandler)`

and

`class ListDefault(tornado.web.RequestHandler)`

`tornado.web.RequestHandler` needs to replaced by `BaseHandler.`

Otherwise all calls to these functions fail to set our custom request headers, methods, and error handling.

**Comment by g0ulash** [comment]
You mean ListDefaults and GetDefault? Good find, thanks! Will be fixed in next push.

**Comment by g0ulash** [comment]
Fixed in c3055c2
