### ISSUE TITLE
Internal Server error on retrieving the list of experiments

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#55]
Reproduction recipe to replicate a 500 internal server when calling the API's exp endpoint.

Do a clean install: install all packages, start the server, and add an admin user by running insert_admin.py in the project's root.

Now retrieve the list of experiments by calling "exp".

Calling this endpoint makes `adminhandlers.py` retrieve the current user object: 
`user = self.get_current_user()`

This user object is then cast to an integer:
`response = db.get_all_experiments(int(user))`

Which generates the following internal server error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado-4.5.2-py3.5-linux-x86_64.egg/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/var/www/sites/pythontest/streamingbandit/app/handlers/adminhandlers.py", line 35, in get
    response = db.get_all_experiments(int(user))
ValueError: invalid literal for int() with base 10: b'admin'
```
Apparently, (sometimes?)  self.get_current_user() returns the name of the user, not the id?

**Comment by robinvanemden** [comment]
The same error is thrown in row 81 and 199 of `adminhandlers.py` - same cause, casting the user variable to int.

**Comment by g0ulash** [comment]
This error occured due to the fact that the admin account had a string as a user_id, instead of the usual int. This is solved by giving the admin account the user_id 0 and the other users a user_id of 1 or greater. Everything should be working again as is (please double check this for me).

**Comment by g0ulash** [comment]
Please also note that for testing you have to create a new admin user! I will supply the new insert_admin.py where necessary.
