### ISSUE TITLE
No REST endpoint to retrieve simulate logs

### ISSUE THREAD

**Issue by robinvanemden** [MKaptein/streamingbandit#57]
Though you can log the results of a simulate call in the database, there is currently no REST call that enables you to retrieve those logs.

**Comment by MKaptein** [comment]
I guess that just goes into the regular logs, so there is no separate “simulate” log… I think that’s fine for now, but perhaps separating them would be nice at some point.

**Comment by g0ulash** [comment]
They do go in a separate database right now, so making such a call should not be hard to do.

**Comment by MKaptein** [comment]
So, we should ;)

Verstuurd vanaf mijn iPad

**Comment by g0ulash** [comment]
Fixed in b10969a. Documentation is updated with new handler and example as well.
