### ISSUE TITLE
Statistics & logging/plots

### ISSUE THREAD

**Issue by g0ulash** [MKaptein/streamingbandit#6]
MKaptein: "Create a number of calls to retrieve:
a. The state of theta (or parts there-off) of an experiment
b. See the "logs"
c. See hourly snapshots of Theta
d. Etc. etc.

Currently rudimentary logging is implemented. But, it would be nice to have (e.g.) snapshots of Theta over time, or to have some plots of data, etc.

wellicht zoiets:

log.theta(theta, names, hourly)

???"

**Comment by MKaptein** [comment]
Er moet een losse API call komen om data op te vragen (met params), en een losse front end voor de plotjes.

**Comment by g0ulash** [comment]
A problem that has risen when logging theta each hour is that we allow experiments to log their theta based on action and context values (e.g. exp:1:theta:action:swim:context:age:20:gender:male), but we do not yet have an easy way to check if this is the case.

One way of solving this is having a flag in the front-end (same as with the loggin the theta hourly has) to make them log theta based on those values or not.

**Comment by g0ulash** [comment]
Examples for existing JS libraries that would be useful:

https://d3js.org/
http://www.chartjs.org/

**Comment by g0ulash** [comment]
We also need to include something for the following critique:

"There is no way to click on an experiment and see its current state and history -- this data is supposedly available by manually entering in URLs defined in the Stats API, but this did not actually work either, as I was only ever able to get an empty dictionary or list returned."
