### ISSUE TITLE
Bigger toolset/libraries

### ISSUE THREAD

**Issue by g0ulash** [MKaptein/streamingbandit#7]
MKaptein: "We need to have methods of storing vectors, matrixes, etc.
We need ways of starting properly.

I think the best way is to start from a simple AB test, and see what tools would be needed to store the data efficiently."

"We need a way to add "modules" to streampy"

**Comment by g0ulash** [comment]
Looking at tools.py and the way we use for example tls.mean and tls.update in the Persuasive example:

Maybe we should make Classes instead of function. So that when I call: mean tls.mean(), I create a class and then later I would like to call mean.update()

**Comment by g0ulash** [comment]
Thinking about this, I am not sure if this would work very well with the way we handle the parametersets (i.e. saving it as a dict in Redis).
We could constraint the classes to have a 'transform' function, such as: tls.mean.to_dict()

And in this case we can save a parameter again by: exp.set_theta(tls.mean.to_dict()).

**Comment by MKaptein** [comment]
Haha, ik mail je net.

Maar, dat kan toch wel werken? binnen set_theta kun je toch gewoon kijken wat voor type object het is, en dan mean.getdict() oid doen? Valt wel een mouw aan te passen.

Ik ga vandaag schrijven…

Groeten,

Maurits

**Comment by MKaptein** [comment]
Ow,

En wat vind je van de naam “StreamingBandit”? Ik vind het eigenlijk niet super. “Strm”? (wat ook direct ruimte bespaart in het paper ;) )…

Of?

**Comment by robinvanemden** [comment]
Strm has my vote :)
