### ISSUE TITLE
Security Feature

### ISSUE THREAD

**Issue by VincentGijsen** [MKaptein/streamingbandit#8]
Perhaps a nice security feature would be a white-list of ip's which may access your management and/or api interface.

This way it is easy to use the tool in production environments and worry less on security holes and possible issues with eval( and user-input which turns out to be poorly escaped)

We might supply the user with an santize-function to strip-out all python/mongodb/redis sensitve strings

**Comment by g0ulash** [comment]
A white-list could be a good idea, however then you still want the separate IPs probably not having access to all the experiment IDs, so you will still need a decent login/authent system for that I presume.

**Comment by MKaptein** [comment]
There is rudimentary login and key-pass pairs for the API calls. Closing this issue now, but it remains an "open-topic" to see how much is needed on the security side.
