### ISSUE TITLE
subset of possible advertisements

### ISSUE THREAD

**Issue by frutik** [MKaptein/streamingbandit#93]
> Online advertising: In online advertising a firm selecting an ad observes the context consisting of a description of the current user visiting a specific webpage. The action is to choose an advertisement out of a set of possible advertisements (possibly dependent on the context itself), and the rewards constitute the clicks on the ad.

Hi All,

Is it possible to choose multiple (n) advertisements (a subset of possible advertisements)?

**Comment by g0ulash** [comment]
This is entirely up to the bandit algorithm that you want to develop and implement, but StreamingBandit definitely allows for this as it is agnostic to the code that you are running. One example of a bandit algorithm that does this, but then for news articles, is: https://dl.acm.org/doi/pdf/10.1145/1772690.1772758

Does this answer your question?

**Comment by frutik** [comment]
> Does this answer your question?

Probably yes. Thank you.

Practical steps are still not clear. But it's something that is possible to do and that's good news. 

So, to have the solution I need to develop something new. It's not possible to use some of the existing templates (with or without customization in just UI), right? 

> but then for news articles,

BTW, the advertisement in my question was just an example, based on the relevant part of your application's description. In reality, they would be elements of UI of a web application. But it changes nothing in the approach, I guess.

**Comment by g0ulash** [comment]
Well, you could adapt some of the existing templates, but it highly depends on your situation - and probably none of the templates suffice for your situation. This is where feature and policy engineering come into place - and the bandit literature might be of help to that. A good start most of the time is to look at the LinUCB algorithm that is in the paper I linked above.

**Comment by frutik** [comment]
Ok. Thank you very much
